version: '3.7'

services:
  toll_client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: toll_client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/client
      - /client/node_modules
    networks:
      - toll_net
    depends_on:
      - toll_server

  toll_server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: toll_server
    env_file:
      - server.env
    ports:
      - '5000:5000'
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - toll_net
    depends_on:
      - toll_postgres

  toll_postgres:
    image: postgres
    container_name: toll_postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - postgres.env
    volumes:
      - toll_postgres:/var/lib/postgresql/data
    networks:
      - toll_net

networks:
  toll_net:
    name: toll_net

volumes:
  toll_postgres:
    driver: local
